version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Bucharest
    volumes:
      - "${DOCKER_VOLUMES_HOME}/syncthing/config:/config"
      - "/home/${USER}:/home/${USER}"
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
