version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_USERNAME} #optional
      - PASS=${TRANSMISSION_PASSWORD}
      - WHITELIST=iplist #optional
    volumes:
      - ${DOCKER_VOLUMES_DIR}/transmission/config:/config
      - ${DOCKER_VOLUMES_DIR}/transmission/downloads:/downloads
      - ${DOCKER_VOLUMES_DIR}/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

